// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int times = Integer.parseInt(args[0]);
	   double countBigger = 0; 
	   double countSmaller = 0;
	   for (int i = 0; i < times; i++){
		double random = Math.random();
		if (random > 0.5){
			countBigger++;
		} else {
			countSmaller++;
		}
	   }
	   System.out.println("> 0.5: " + countBigger + " times");
	   System.out.println("<= 0.5: " + countSmaller + " times");
	   if (countBigger != 0 && countSmaller != 0 ) { 
	   System.out.println("Ratio: " + ((double)(countBigger / countSmaller)));
	   }  
	}
}
